spring.application.name=demorest4

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalmanagement
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=pushpey
spring.security.user.password=1234